In [1]:
5/2

2.5

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stock_data.csv",skiprows=1)
df

# or you can use header as read_csv(file,header=1)

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [3]:
df = pd.read_csv('stock_data.csv',header=1,names=['stock_sym','eps','revenue','price','ceo'])
df

  stock_sym            eps  revenue price            ceo
0     GOOGL          27.82       87   845     larry page
1       WMT           4.61      484    65           n.a.
2      MSFT             -1       85    64     bill gates
3      RIL   not available       50  1023  mukesh ambani
4      TATA            5.6       -1  n.a.     ratan tata

In [4]:
df = pd.read_csv("stock_data.csv",skiprows=1, nrows=2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [5]:
df = pd.read_csv(
    "stock_data.csv",
    skiprows=1,
    na_values={
        'eps': ['not available','-1'],
        'revenue': ['-1'],
        'price': ['n.a.'],
        'people' : ['n.a.']
    }
)
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [2]:
df = pd.read_csv(
    "stock_data.csv",
    skiprows=1,
    na_values=['not available','n.a.','-1'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [3]:
df['pe_ratio'] = df['price'] / df['eps']
df

  tickers    eps  revenue   price         people   pe_ratio
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [4]:
df.to_csv('pe.csv',index=False)

In [6]:
df_movies = pd.read_excel('movies_db.xlsx',"movies")
df_movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [7]:
df_financials = pd.read_excel('movies_db.xlsx',"financials")
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [9]:
def standard_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials = pd.read_excel('movies_db.xlsx',"financials", converters={
    'currency' : standard_currency
})
df_financials

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions      USD
3        104    180.00     854.0   Millions      USD
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD

In [12]:
df_merged = pd.merge(df_movies,df_financials, on="movie_id")
df_merged.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

In [13]:
df_merged.to_excel('movies_merged.xlsx',sheet_name='merged', index=False)

In [19]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL','WMT','MSFT'],	
    'eps': [27.82,4.61,'NaN',],	
    'price': [30.37,14.56,30.97],
    'people': ['larry page','Nan','bill gates']
})
df_stocks

  tickers    eps  price      people
0   GOOGL  27.82  30.37  larry page
1     WMT   4.61  14.56         Nan
2    MSFT    NaN  30.97  bill gates

In [20]:
df_weather = pd.DataFrame({
    'day':['1/1/2026','1/2/2026','1/3/2026'],
    'temp':[32,45,12],
    'event':['rain','sunny','snow']
})
df_weather

        day  temp  event
0  1/1/2026    32   rain
1  1/2/2026    45  sunny
2  1/3/2026    12   snow

In [22]:
with pd.ExcelWriter("stocks_weather.xlsx") as writer:
    df_stocks.to_excel(writer, sheet_name='stocks')
    df_weather.to_excel(writer, sheet_name='weater')